

const enum Constants {
  INIT_USER = "INIT_USER",
  CHANGE_NAME = "CHANGE_NAME",
  CHANGE_PARAMETRS = "CHANGE_PARAMETRS",
  UP_SKILLS = "UP_SKILLS",
  TAKE_DAMAGE_USER = "TAKE_DAMAGE_USER",
  UPLOAD_CHARACTER = "UPLOAD_CHARACTER",
}

export { Constants };
